// 95 Larnaca projects from 8 developers (only AVAILABLE, not sold/completed).
// User confirmed: skip sold, only active. Africanos had ~40 historically but only 10 are active.
export const LARNACA_PROJECTS = [
    // ===== PLUS PROPERTIES (18) =====
    { dev: 'Plus Properties', name: 'PLUS 21 ROY TERRACES', area: 'Mackenzie',           url: 'https://www.pluspropertiescyprus.com/plus-21-roy-terraces---mackenzie/59' },
    { dev: 'Plus Properties', name: 'PLUS 38',              area: 'Mackenzie',           url: 'https://www.pluspropertiescyprus.com/plus-38---mackenzie/76' },
    { dev: 'Plus Properties', name: 'PLUS 57 TAMARA GARDENS 2', area: 'Livadia',         url: 'https://www.pluspropertiescyprus.com/plus-57-tamara-gardens-2---livadia/99' },
    { dev: 'Plus Properties', name: 'Plus 59',              area: 'Larnaca City Center', url: 'https://www.pluspropertiescyprus.com/plus-59---new-mall-area/98' },
    { dev: 'Plus Properties', name: 'PLUS 61',              area: 'Larnaca City Center', url: 'https://www.pluspropertiescyprus.com/plus-61---faneromeni/108' },
    { dev: 'Plus Properties', name: 'Plus 62',              area: 'Livadia',             url: 'https://www.pluspropertiescyprus.com/plus-62---livadia/104' },
    { dev: 'Plus Properties', name: 'PLUS 65',              area: 'Larnaca City Center', url: 'https://www.pluspropertiescyprus.com/plus-65---faneromeni/110' },
    { dev: 'Plus Properties', name: 'PLUS 66',              area: 'Larnaca City Center', url: 'https://www.pluspropertiescyprus.com/plus-66---faneromeni/111' },
    { dev: 'Plus Properties', name: 'PLUS 70-71',           area: 'Marina',              url: 'https://www.pluspropertiescyprus.com/plus-70-71---new-marina/113' },
    { dev: 'Plus Properties', name: 'Plus 74',              area: 'Larnaca City Center', url: 'https://www.pluspropertiescyprus.com/plus-74---downtown/118' },
    { dev: 'Plus Properties', name: 'PLUS 75',              area: 'Kiti',                url: 'https://www.pluspropertiescyprus.com/plus-75---kiti/121' },
    { dev: 'Plus Properties', name: 'Plus 77',              area: 'Mackenzie',           url: 'https://www.pluspropertiescyprus.com/plus-77---mackenzie/122' },
    { dev: 'Plus Properties', name: 'Plus 79',              area: 'Livadia',             url: 'https://www.pluspropertiescyprus.com/plus-79---livadia/123' },
    { dev: 'Plus Properties', name: 'Plus 80',              area: 'Livadia',             url: 'https://www.pluspropertiescyprus.com/plus-80-livadia/124' },
    { dev: 'Plus Properties', name: 'Plus 81',              area: 'Larnaca City Center', url: 'https://www.pluspropertiescyprus.com/plus-81---downtown/126' },
    { dev: 'Plus Properties', name: 'Plus 82',              area: 'Larnaca City Center', url: 'https://www.pluspropertiescyprus.com/plus-82---downtown/127' },
    { dev: 'Plus Properties', name: 'Plus 87',              area: 'Marina',              url: 'https://www.pluspropertiescyprus.com/plus-87---new-marina/134' },
    { dev: 'Plus Properties', name: 'Plus 88',              area: 'Larnaca City Center', url: 'https://www.pluspropertiescyprus.com/plus-88---downtown/133' },

    // ===== DEXTEK GROUP (25) =====
    { dev: 'DexTek Group', name: 'Destiny Residence',     area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=823' },
    { dev: 'DexTek Group', name: 'Velvet Residence',      area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=803' },
    { dev: 'DexTek Group', name: 'Horizon Towers',        area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=833' },
    { dev: 'DexTek Group', name: 'Golden Park II',        area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=793' },
    { dev: 'DexTek Group', name: 'Aurora Residence (DexTek)', area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=784' },
    { dev: 'DexTek Group', name: 'The Jewel',             area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=648' },
    { dev: 'DexTek Group', name: 'San Sousi Development', area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=471' },
    { dev: 'DexTek Group', name: 'The Central II',        area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=747' },
    { dev: 'DexTek Group', name: 'Lorelei Residence',     area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=500' },
    { dev: 'DexTek Group', name: 'Silverstone Residence', area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=570' },
    { dev: 'DexTek Group', name: 'The Central',           area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=639' },
    { dev: 'DexTek Group', name: 'Golden Park',           area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=666' },
    { dev: 'DexTek Group', name: 'Glamour Residence',     area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=757' },
    { dev: 'DexTek Group', name: 'Paradise Residence',    area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=684' },
    { dev: 'DexTek Group', name: 'Savoy Residence',       area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=607' },
    { dev: 'DexTek Group', name: 'Allure Residence',      area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=618' },
    { dev: 'DexTek Group', name: 'Onyx Residence',        area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=559' },
    { dev: 'DexTek Group', name: 'Lumina Mare',           area: 'Mackenzie',           url: 'https://www.dextekgroup.com/publish_project.php?id=852' },
    { dev: 'DexTek Group', name: 'Finix Residence',       area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=583' },
    { dev: 'DexTek Group', name: 'Aqua Parkview Residence', area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=531' },
    { dev: 'DexTek Group', name: 'Hamilton Residence',    area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=628' },
    { dev: 'DexTek Group', name: 'La Vida Residence',     area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=717' },
    { dev: 'DexTek Group', name: 'Infinite Residence',    area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=834' },
    { dev: 'DexTek Group', name: 'Palm 2',                area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=733' },
    { dev: 'DexTek Group', name: 'Palm 1',                area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=724' },
    { dev: 'DexTek Group', name: 'Mari-Blu Residence II', area: 'Mackenzie',           url: 'https://www.dextekgroup.com/publish_project.php?id=470' },
    { dev: 'DexTek Group', name: 'Vista Del Mare',        area: 'Mackenzie',           url: 'https://www.dextekgroup.com/publish_project.php?id=675' },
    { dev: 'DexTek Group', name: 'One & One Residences',  area: 'Larnaca City Center', url: 'https://www.dextekgroup.com/publish_project.php?id=843' },

    // ===== INFINITY PROPERTIES (14) =====
    { dev: 'Infinity Properties', name: 'Palm Residence',      area: 'Oroklini',            url: 'https://www.infinityproperties.com.cy/palm-residence/' },
    { dev: 'Infinity Properties', name: 'Aqua Residence',      area: 'Livadia',             url: 'https://www.infinityproperties.com.cy/aqua-residence/' },
    { dev: 'Infinity Properties', name: 'Coral Residence',     area: 'Mackenzie',           url: 'http://www.infinityproperties.com.cy/coral-residence/' },
    { dev: 'Infinity Properties', name: 'Marina Home Residence', area: 'Marina',            url: 'https://www.infinityproperties.com.cy/marina-home-residence/' },
    { dev: 'Infinity Properties', name: 'Kalymnos Residence',  area: 'Larnaca City Center', url: 'https://www.infinityproperties.com.cy/kalymnos-residence/' },
    { dev: 'Infinity Properties', name: 'Lotus Residence',     area: 'Livadia',             url: 'https://www.infinityproperties.com.cy/lotus-residence/' },
    { dev: 'Infinity Properties', name: 'Serenity Residence',  area: 'Drosia',              url: 'https://www.infinityproperties.com.cy/serenity-residence/' },
    { dev: 'Infinity Properties', name: 'Infinity Central',    area: 'Larnaca City Center', url: 'https://www.infinityproperties.com.cy/infinity-central/' },
    { dev: 'Infinity Properties', name: 'Hydra Residence',     area: 'Oroklini',            url: 'https://www.infinityproperties.com.cy/hydra-residence/' },
    { dev: 'Infinity Properties', name: 'Orchidea Residence',  area: 'Larnaca City Center', url: 'http://www.infinityproperties.com.cy/orchidea-residence/' },
    { dev: 'Infinity Properties', name: 'Harmonia Residence',  area: 'Larnaca City Center', url: 'https://www.infinityproperties.com.cy/harmonia-residence/' },
    { dev: 'Infinity Properties', name: 'Riviera Residence (Infinity)',   area: 'Livadia',  url: 'https://www.infinityproperties.com.cy/riviera-residence/' },
    { dev: 'Infinity Properties', name: 'Aurora Residence (Infinity)',    area: 'Marina',   url: 'https://www.infinityproperties.com.cy/aurora-residence/' },
    { dev: 'Infinity Properties', name: 'Reef Residence',      area: 'Mackenzie',           url: 'http://www.infinityproperties.com.cy/reef-residence/' },

    // ===== AFRICANOS (10) =====
    { dev: 'Africanos Property Developers', name: 'Sunstone Residences Block A', area: 'Larnaca City Center', url: 'https://africanosproperties.com/project/sunstone-residences-block-a-under-study-completion-year-2028/' },
    { dev: 'Africanos Property Developers', name: 'Mackenzy Star Residences',    area: 'Mackenzie',           url: 'https://africanosproperties.com/project/mackenzy-star-residences-coming-soon/' },
    { dev: 'Africanos Property Developers', name: 'Serenity Residences (Africanos)', area: 'Aradippou',       url: 'https://africanosproperties.com/project/serenity-residences/' },
    { dev: 'Africanos Property Developers', name: 'Kiti Magic Residences',       area: 'Kiti',                url: 'https://africanosproperties.com/project/kiti-magic-residences/' },
    { dev: 'Africanos Property Developers', name: 'Marina Riviera Residences',   area: 'Marina',              url: 'https://africanosproperties.com/project/marina-riviera-residences/' },
    { dev: 'Africanos Property Developers', name: 'Central Park Residences',     area: 'Larnaca City Center', url: 'https://africanosproperties.com/project/central-park-residences-under-study-completion-end-of-december-2028/' },
    { dev: 'Africanos Property Developers', name: 'Amber Residences',            area: 'Larnaca City Center', url: 'https://africanosproperties.com/project/amber-residences-under-study-completion-december-2027/' },
    { dev: 'Africanos Property Developers', name: 'Marina Riviera Residences Block A', area: 'Marina',        url: 'https://africanosproperties.com/project/marina-riviera-residences/marina-riviera-residences-block-a-completion-year-2028/' },
    { dev: 'Africanos Property Developers', name: 'Ruby Residences',             area: 'Larnaca City Center', url: 'https://africanosproperties.com/project/ruby-residences-under-study-completion-december-2027/' },
    { dev: 'Africanos Property Developers', name: 'Amethyst Residences',         area: 'Larnaca City Center', url: 'https://africanosproperties.com/project/amethyst-residences-under-study-completion-december-2027/' },

    // ===== NEW ZOE DEVELOPERS (8) =====
    { dev: 'New Zoe Developers', name: 'Oroklini Hills View',     area: 'Oroklini',            url: 'https://newzoedevelopers.com/en/projects/2194857' },
    { dev: 'New Zoe Developers', name: 'Palourtis House',         area: 'Dhekelia',            url: 'https://newzoedevelopers.com/en/projects/2148361' },
    { dev: 'New Zoe Developers', name: 'Sophia Gardens',          area: 'Pyla',                url: 'https://newzoedevelopers.com/en/projects/2171180' },
    { dev: 'New Zoe Developers', name: 'Beachfront Land Ormidia', area: 'Dhekelia',            url: 'https://newzoedevelopers.com/en/projects/2273252' },
    { dev: 'New Zoe Developers', name: 'Beach Front Ormidia Villa', area: 'Dhekelia',          url: 'https://newzoedevelopers.com/en/projects/2171283' },
    { dev: 'New Zoe Developers', name: 'Anna Court Livadia',      area: 'Livadia',             url: 'https://newzoedevelopers.com/en/projects/2171139' },
    { dev: 'New Zoe Developers', name: 'Academia Tower',          area: 'Larnaca City Center', url: 'https://newzoedevelopers.com/en/projects/2171196' },
    { dev: 'New Zoe Developers', name: 'Charalambos Residences',  area: 'Livadia',             url: 'https://newzoedevelopers.com/en/projects/2151283' },

    // ===== EDGE DEVELOPMENT GROUP (7) =====
    { dev: 'Edge Development Group', name: 'Park Avenue (Edge)',        area: 'Larnaca City Center', url: 'https://www.edgedevelopment.eu/projects/park-avenue/' },
    { dev: 'Edge Development Group', name: 'Sea Gallery by Edge',       area: 'Mackenzie',           url: 'https://www.edgedevelopment.eu/projects/sea-gallery-by-edge/' },
    { dev: 'Edge Development Group', name: 'Krasas Hillside Residences', area: 'Larnaca City Center', url: 'https://www.edgedevelopment.eu/projects/krasas-hillside-residences/' },
    { dev: 'Edge Development Group', name: 'Edge One Residence',        area: 'Larnaca City Center', url: 'https://www.edgedevelopment.eu/projects/edge-one-residence/' },
    { dev: 'Edge Development Group', name: 'Edge Residences',           area: 'Aradippou',           url: 'https://www.edgedevelopment.eu/projects/edge-residences/' },
    { dev: 'Edge Development Group', name: 'Floating Scapes',           area: 'Marina',              url: 'https://www.edgedevelopment.eu/projects/floating-scapes/' },
    { dev: 'Edge Development Group', name: 'Pandora Residence',         area: 'Larnaca City Center', url: 'https://www.edgedevelopment.eu/projects/pandora-residence/' },

    // ===== PANIKKOS LIVADIOTIS GROUP (7) =====
    { dev: 'Panikkos Livadiotis Group', name: 'Eleyia Deluxe Villa',  area: 'Dhekelia',            url: 'https://www.livadiotis.com/index.php/properties/villas/eleyia-dhekelia-larnaca' },
    { dev: 'Panikkos Livadiotis Group', name: 'Plot 786 Dionysus Villas', area: 'Pyla',           url: 'https://www.livadiotis.com/index.php/properties/villas/plot-786-dionysus-villas' },
    { dev: 'Panikkos Livadiotis Group', name: 'Villa Azure',          area: 'Marina',              url: 'https://www.livadiotis.com/index.php/properties/villas/azure-palm-beach-larnaca-cyprus-113' },
    { dev: 'Panikkos Livadiotis Group', name: 'Ria Court 87',         area: 'Drosia',              url: 'https://www.livadiotis.com/index.php/properties/apartments/ria-court-87-drosia-hill-larnaca' },
    { dev: 'Panikkos Livadiotis Group', name: 'Ria Court 86',         area: 'Larnaca City Center', url: 'https://www.livadiotis.com/index.php/properties/apartments/larnaca-investment-apartments-building' },
    { dev: 'Panikkos Livadiotis Group', name: 'Ria Court 63-67',      area: 'Larnaca City Center', url: 'https://www.livadiotis.com/index.php/properties/apartments/ria-court-66-lakeside-boulevard' },
    { dev: 'Panikkos Livadiotis Group', name: 'Ria Court 89',         area: 'Larnaca City Center', url: 'https://www.livadiotis.com/index.php/properties/apartments/ria-court-89' },

    // ===== MARINAKIS PROPERTY DEVELOPERS (6) =====
    { dev: 'Marinakis Property Developers', name: 'Marigate',             area: 'Marina',              url: 'https://marinakisproperties.vercel.app/marigate.html' },
    { dev: 'Marinakis Property Developers', name: 'Palma Fiore',          area: 'Livadia',             url: 'https://marinakisproperties.vercel.app/' },
    { dev: 'Marinakis Property Developers', name: 'Sun Valley Residences', area: 'Marina',             url: 'https://marinakisproperties.vercel.app/' },
    { dev: 'Marinakis Property Developers', name: 'Fire Station Maisonettes', area: 'Dhekelia',        url: 'https://marinakisproperties.vercel.app/' },
    { dev: 'Marinakis Property Developers', name: 'Lakeview Villas',      area: 'Larnaca City Center', url: 'https://marinakisproperties.vercel.app/' },
    { dev: 'Marinakis Property Developers', name: 'Pearl House 11',       area: 'Marina',              url: 'https://marinakisproperties.vercel.app/' }
];

// Larnaca area centers for fallback GPS
export const LARNACA_AREA_CENTERS = {
    'Larnaca City Center': [34.9166, 33.6304],
    'Finikoudes':          [34.9192, 33.6388],
    'Mackenzie':           [34.8854, 33.6406],
    'Marina':              [34.9211, 33.6428],
    'Pyla':                [34.9758, 33.6772],
    'Livadia':             [34.9237, 33.6500],
    'Oroklini':            [34.9522, 33.6533],
    'Aradippou':           [34.9233, 33.6055],
    'Drosia':              [34.9269, 33.6244],
    'Kamares Larnaca':     [34.9263, 33.6133],
    'Kiti':                [34.8418, 33.5723],
    'Anglisides':          [34.8989, 33.5311],
    'Dhekelia':            [34.9697, 33.7000]
};
